### PR TITLE
Support for sidekiq 7

### PR DESCRIPTION
**Pull request by jpaas**
Fixes several incompatibilities with the new `redis-client` used by Sidekiq 7 as discussed in #66

### CODE REVIEW

**Comment by nglx** [comment]
@jpaas can you take a look at the failing specs?

**Comment by jpaas** [comment]
> @jpaas can you take a look at the failing specs?

@nglx I fixed most of the failing tests I think. But not all. fakeredis doesn't appear to work with sidekiq 7. If I disable it as the sidekiq driver a lot of the tests pass. But there are 12 tests failing in `status_spec.rb`. Without spending a lot more time learning about how sidekiq-batch works I can't really understand their intent or why they aren't working.

**Comment by remy727** [comment]
Any updates on this?

**Comment by JacksonRiso** [comment]
Would love this as well!

**Comment by matteeyah** [comment]
@jpaas @nglx Love the work that's been done so far. Any updates on this?

**Comment by lukinski** [comment]
Does it help somehow? https://github.com/jpaas/sidekiq-batch/pull/1. All specs should pass.

**Pull request closed without merging**
