### PR TITLE
Finalize Callbacks Followup

### PR DESCRIPTION
**Pull request by jbrady42**
This integrates the callback finalize changes from #26 with the latest in master.

All integration tests are now passing.

### CODE REVIEW

**Comment by managr** [comment]
@jbrady42 that looks good! Merging to master for some further testing. Thank you!

**Comment by damau** [comment]
Hi, I've used this and it's brilliant.  Could we please create a release for it?

**Comment by gnagno** [comment]
I agree with @damau , can we please create a gem from this?

**Comment by managr** [comment]
@damau @gnagno released 0.1.6 with it.
@jbrady42 thanks a lot for it.

**Comment by damau** [comment]
Thanks @jbrady42 and @managr !!! 🎉

**Pull request merged**
