### PR TITLE
Ensure batch callbacks aren't run unexpectedly

### PR DESCRIPTION
**Pull request by aleksclark**
This PR addresses a race condition present when jobs are added to a batch that complete before the adder is done. I've also pinned the sidekiq requirement under 7 because specs fail with sidekiq 7.

here is a minimal repro:
```ruby
class BatchTestWorker
  include Sidekiq::Worker

  def perform(spawn_children)
    if spawn_children
      log('spawner started')
      batch.jobs do
        5.times do
          BatchTestWorker.perform_async(false)
          sleep 5
        end
      end
      log('spawner ended')
    else
      log('child run')
    end
  end

  def bulk_logger
    @@bulk_logger ||= Logger.new("#{Rails.root}/log/bulk.log")
  end

  def log(msg)
    bulk_logger.info(msg)
  end
end

class TestCallback

  def on_complete(status, options)
    log("callback - complete")
  end

  def on_success(status, options)
    log("callback - success")
  end

  def bulk_logger
    @@bulk_logger ||= Logger.new("#{Rails.root}/log/bulk.log")
  end

  def log(msg)
    bulk_logger.info(msg)
  end
end
```

Called like so:

```ruby
  batch = Sidekiq::Batch.new
  batch.on(:success, TestCallback)
  batch.on(:complete, TestCallback)
  batch.jobs do
    BatchTestWorker.perform_async(true)
  end
```

Pre-fix result:
```
I, [2022-12-16T09:04:50.927633 #3662974]  INFO -- : spawner started
I, [2022-12-16T09:04:51.174733 #3662973]  INFO -- : child run
I, [2022-12-16T09:04:51.179701 #3662973]  INFO -- : callback - success
I, [2022-12-16T09:04:51.425542 #3662972]  INFO -- : callback - complete
I, [2022-12-16T09:04:55.934796 #3662972]  INFO -- : child run
I, [2022-12-16T09:05:00.935667 #3662973]  INFO -- : child run
I, [2022-12-16T09:05:05.936724 #3662972]  INFO -- : child run
I, [2022-12-16T09:05:10.938245 #3662973]  INFO -- : child run
I, [2022-12-16T09:05:15.933752 #3662974]  INFO -- : spawner ended
```

Post-fix result:
```
I, [2022-12-16T13:02:53.446592 #3765663]  INFO -- : spawner started
I, [2022-12-16T13:02:53.447583 #3765663]  INFO -- : spawner sleeping...
I, [2022-12-16T13:02:58.448737 #3765663]  INFO -- : spawner sleeping...
I, [2022-12-16T13:03:03.449961 #3765663]  INFO -- : spawner sleeping...
I, [2022-12-16T13:03:07.345600 #3765662]  INFO -- : child run
I, [2022-12-16T13:03:07.349631 #3765662]  INFO -- : child run
I, [2022-12-16T13:03:07.506709 #3765661]  INFO -- : child run
I, [2022-12-16T13:03:08.451440 #3765663]  INFO -- : spawner sleeping...
I, [2022-12-16T13:03:13.452781 #3765663]  INFO -- : spawner sleeping...
I, [2022-12-16T13:03:15.095986 #3765662]  INFO -- : child run
I, [2022-12-16T13:03:18.453816 #3765663]  INFO -- : spawner ended
I, [2022-12-16T13:03:23.160604 #3765662]  INFO -- : child run
I, [2022-12-16T13:03:23.207821 #3765663]  INFO -- : callback - success
I, [2022-12-16T13:03:23.207821 #3765661]  INFO -- : callback - complete
```

### CODE REVIEW

**Review by nglx — APPROVED** [review]

**Comment by nglx** [comment]
Thank you @aleksclark, will test a bit and release a new version

**Comment by Mates91** [comment]
@nglx Hi guys, is there a release scheduled? Thanks for your work!

**Comment by mhenrixon** [comment]
@nglx any chance we could get a new release?

**Comment by Mates91** [comment]
> @nglx any chance we could get a new release?

Do you try using a gem with this PR?

**Comment by lionelchauvin** [comment]
@aleksclark your PR was not working for me. Would you have time to review my PR ?
This particular [test](https://github.com/breamware/sidekiq-batch/pull/100/files#diff-37331ed42f1713ac6a63541541e25405acdeedbf712371fc08c52c1a790589abR189) describes the problem.

**Pull request merged**
