### PR TITLE
Don't hide exceptions

### PR DESCRIPTION
**Pull request by infinite-monkeys**
For #13

### CODE REVIEW

**Comment by managr** [comment]
Thanks for the fix. Merging.

**Comment by infinite-monkeys** [comment]
Whoops -- we apparently didn't run the tests here (or just ignored that they were broken).  I should have noticed that before submitting.

**Comment by managr** [comment]
Can you open another PR fixing specs?

**Comment by infinite-monkeys** [comment]
I don't see a spec fix in our internal repo. Can't promise anything, but I'll see what I can do.

**Pull request merged**
