### PR TITLE
add support for sidekiq 7

### PR DESCRIPTION
**Pull request by JacobBriggsAckama**

### CODE REVIEW

**Comment by G-Rath** [comment]
Does this retain compatibility with older versions of Sidekiq, or should we be guarding against `Sidekiq::VERSION`?

**Comment by JacobBriggsAckama** [comment]
> Does this retain compatibility with older versions of Sidekiq, or should we be guarding against `Sidekiq::VERSION`?

good point, its probably not compatible so I'll guard

**Comment by trostli** [comment]
Can this be merged in @nglx ?

**Comment by ragingdave** [comment]
@aleksclark @nglx Maybe this can be a christmas present to add Sidekiq 7 support?

**Comment by aleksclark** [comment]
> @aleksclark @nglx Maybe this can be a christmas present to add Sidekiq 7 support?

I don't have the powah sorry

**Review by nglx — APPROVED** [review]

**Comment by rkotov93** [comment]
Seems like this pull request broke specs as `fakeredis` doesn't support `redis-client` which is dependency for Sidekiq 7. Here are more details  https://github.com/guilleiguaran/fakeredis/issues/270

**Comment by lukinski** [comment]
Can we just use Redis as an external dependency service for RSpec purposes, instead of faking it? I find it as a rescue option, at least for the time when it's not possible to stub Redis together with `redis-client`. @nglx what do you think?

**Pull request merged**
